// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_chirp_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpByID = `-- name: DeleteChirpByID :execrows
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChirpByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChirpByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
