// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_login_by_userID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateLoginByUserID = `-- name: UpdateLoginByUserID :one
UPDATE users
SET updated_at = NOW(), email = $2, hashed_password = $3
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateLoginByUserIDParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateLoginByUserID(ctx context.Context, arg UpdateLoginByUserIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateLoginByUserID, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
