// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upgrade_user_to_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserToChirpyRed = `-- name: UpgradeUserToChirpyRed :execrows
UPDATE users
SET is_chirpy_red = true
WHERE id = $1
`

func (q *Queries) UpgradeUserToChirpyRed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, upgradeUserToChirpyRed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
